language: python
python:
    - "pypy"
install:
    - "git clone git@github.com:kevinburke/requests.git"
    - "cd requests"
    - "git checkout connect"
    - "make init"
script: 
    - "pypy --version"
    - "make test"
